# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: deploy to bos repo

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up BoS maven repo
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 1.8
        server-id: bos-repo # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: BOS_REPO_AK # env variable for username in deploy
        server-password: BOS_REPO_SK # env variable for token in deploy

    - name: Publish to Apache Maven Central
      run: mvn clean deploy -P bos-deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        BOS_REPO_AK: ${{ secrets.BOS_REPO_AK }}
        BOS_REPO_SK: ${{ secrets.BOS_REPO_SK }}
